export const projects = [
  {
    bannerUrl: 'https://www.craftz.dog/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Finkdrop_eyecatch.b6e3cf29.png&w=750&q=75',
    title: 'Inkdrop',
    description: 'A Markdown note-taking app with 100+ plugins, cross-platform and encrypted data sync support. The life-time revenue is more than $300k.',
    liveUrl: 'https://www.inkdrop.app/',
    platform: 'Windows/macOS/Linux/iOS/Android',
    stack: 'NodeJS, Electron, React Native',
    blogUrl: 'https://blog.inkdrop.app/how-ive-attracted-the-first-500-paid-users-for-my-saas-that-costs-5-mo-7a5b94b8e820',
    snapshot: 'https://www.craftz.dog/images/works/inkdrop_02.png', 
  },
  {
    bannerUrl: 'https://www.craftz.dog/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Finkdrop_eyecatch.b6e3cf29.png&w=750&q=75',
    title: 'Inkdrop',
    description: 'A Markdown note-taking app with 100+ plugins, cross-platform and encrypted data sync support. The life-time revenue is more than $300k.',
    liveUrl: 'https://www.inkdrop.app/',
    platform: 'Windows/macOS/Linux/iOS/Android',
    stack: 'NodeJS, Electron, React Native',
    blogUrl: 'https://blog.inkdrop.app/how-ive-attracted-the-first-500-paid-users-for-my-saas-that-costs-5-mo-7a5b94b8e820',
    snapshot: 'https://www.craftz.dog/images/works/inkdrop_02.png', 
  },
  {
    bannerUrl: 'https://www.craftz.dog/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Finkdrop_eyecatch.b6e3cf29.png&w=750&q=75',
    title: 'Inkdrop',
    description: 'A Markdown note-taking app with 100+ plugins, cross-platform and encrypted data sync support. The life-time revenue is more than $300k.',
    liveUrl: 'https://www.inkdrop.app/',
    platform: 'Windows/macOS/Linux/iOS/Android',
    stack: 'NodeJS, Electron, React Native',
    blogUrl: 'https://blog.inkdrop.app/how-ive-attracted-the-first-500-paid-users-for-my-saas-that-costs-5-mo-7a5b94b8e820',
    snapshot: 'https://www.craftz.dog/images/works/inkdrop_02.png', 
  },
  {
    bannerUrl: 'https://www.craftz.dog/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Finkdrop_eyecatch.b6e3cf29.png&w=750&q=75',
    title: 'Inkdrop',
    description: 'A Markdown note-taking app with 100+ plugins, cross-platform and encrypted data sync support. The life-time revenue is more than $300k.',
    liveUrl: 'https://www.inkdrop.app/',
    platform: 'Windows/macOS/Linux/iOS/Android',
    stack: 'NodeJS, Electron, React Native',
    blogUrl: 'https://blog.inkdrop.app/how-ive-attracted-the-first-500-paid-users-for-my-saas-that-costs-5-mo-7a5b94b8e820',
    snapshot: 'https://www.craftz.dog/images/works/inkdrop_02.png', 
  },
];
