import React from 'react'
import Head from 'next/head'
import { Text, VStack, chakra, shouldForwardProp  } from '@chakra-ui/react'
import { motion } from 'framer-motion'
import Navigation from '@/core/navigation'
import Jumbotron from '@/core/jumbotron'

const StyledContainer = chakra(motion.div, {
  shouldForwardProp: prop => {
    return shouldForwardProp(prop) || prop === 'transition'
  }
})

const Layout = ({ pageTitle, children }) => {
  const lightBg = `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='100%25' width='100%25'%3E%3Cdefs%3E%3Cpattern id='doodad' width='26' height='26' viewBox='0 0 40 40' patternUnits='userSpaceOnUse' patternTransform='rotate(22)'%3E%3Crect width='100%25' height='100%25' fill='rgba(255, 255, 255, 1)'/%3E%3Cpath d='M-1 20h2v1h-2zM39 20h2v1h-2z' fill='rgba(57, 52, 55, 1)'/%3E%3Cpath d='M19.5 20h1v1h-1zM59.5 20h1v1h-1z' fill='rgba(251, 182, 206, 1)'/%3E%3C/pattern%3E%3C/defs%3E%3Crect fill='url(%23doodad)' height='200%25' width='200%25'/%3E%3C/svg%3E ")`
  
  return (
    <VStack
      minH='100vh'
      minW='100vw'
      overflowY='auto'
      background={lightBg}
    >
      <Head>
        <title>{pageTitle} - devzana.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/face-logo.svg" />
      </Head>
      <Navigation />
      <VStack w='100%' maxW='container.lg'>
        <Jumbotron />
        <StyledContainer
          initial={{ y: 10, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.8, delay: 0.1 }}
          mb={6}
        >
          {children}
        </StyledContainer>
      </VStack>
      <Text pt={16} color='rgba(57, 52, 55, 0.44)'>
        © 2023 Sean Christian Lozana. All Rights Reserved.
      </Text>
    </VStack>
  )
}

export default Layout